/**
 * LLMemory-Palace v25.0 - Reconstructor
 * Reconstructs source files from CXML or genome
 */

import fs from 'fs';
import path from 'path';
import { GenomeEncoder } from './genome.js';
import { PatternLibrary } from './patterns.js';

export class Reconstructor {
  constructor() {
    this.genomeEncoder = new GenomeEncoder();
    this.patternLibrary = new PatternLibrary();
  }

  /**
   * Reconstruct source from CXML or genome file
   */
  async rebuild(inputFile, outputDir = './reconstructed') {
    const content = fs.readFileSync(inputFile, 'utf-8');
    
    // Detect format
    if (content.includes('<PALACE')) {
      await this._reconstructFromCxml(content, outputDir);
    } else if (content.startsWith('GENOME|')) {
      await this._reconstructFromGenome(content, outputDir);
    } else {
      throw new Error('Unknown format. Expected CXML or genome.');
    }

    return outputDir;
  }

  /**
   * Reconstruct from CXML format
   */
  async _reconstructFromCxml(cxmlContent, outputDir) {
    // Create output directory
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Extract files from CXML
    const fileRegex = /<Φ[^>]*path="([^"]+)"[^>]*>[\s\S]*?<C><!\[CDATA\[([\s\S]*?)\]\]><\/C>[\s\S]*?<\/Φ>/g;
    let match;

    while ((match = fileRegex.exec(cxmlContent)) !== null) {
      const filePath = match[1];
      let content = match[2];

      // Unescape CDATA
      content = content.replace(/\]\]\]\]><!\[CDATA\[>/g, ']]>');

      // Create full path
      const fullPath = path.join(outputDir, filePath);
      const dir = path.dirname(fullPath);

      // Ensure directory exists
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      // Write file
      fs.writeFileSync(fullPath, content, 'utf-8');
      console.log(`  Reconstructed: ${filePath}`);
    }
  }

  /**
   * Reconstruct from one-line genome format
   */
  async _reconstructFromGenome(genomeString, outputDir) {
    // Create output directory
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const genome = this.genomeEncoder.decode(genomeString);
    const files = this.genomeEncoder.reconstruct(genomeString, outputDir);

    // Write each file
    for (const file of files) {
      const fullPath = path.join(outputDir, file.path);
      const dir = path.dirname(fullPath);

      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      fs.writeFileSync(fullPath, file.content, 'utf-8');
      console.log(`  Reconstructed: ${file.path}`);
    }

    // Also generate flows
    for (const flow of genome.flows) {
      const flowContent = this._generateFlowFile(flow);
      const flowPath = path.join(outputDir, 'flows', `${flow.name}_flow.js`);
      
      const flowDir = path.dirname(flowPath);
      if (!fs.existsSync(flowDir)) {
        fs.mkdirSync(flowDir, { recursive: true });
      }
      
      fs.writeFileSync(flowPath, flowContent, 'utf-8');
      console.log(`  Generated flow: ${flow.name}`);
    }

    // Generate config
    const configPath = path.join(outputDir, 'config.json');
    fs.writeFileSync(configPath, JSON.stringify(genome.config, null, 2), 'utf-8');
    console.log(`  Generated config: config.json`);
  }

  /**
   * Generate flow file from flow definition
   */
  _generateFlowFile(flow) {
    let content = `/**\n * Flow: ${flow.name}\n * Auto-generated by LLMemory-Palace\n */\n\n`;
    content += `async function ${flow.name}() {\n`;
    
    for (let i = 0; i < flow.steps.length; i++) {
      content += `  // Step ${i + 1}: ${flow.steps[i]}\n`;
      content += `  await ${flow.steps[i]}();\n\n`;
    }
    
    content += `  return result;\n`;
    content += `}\n`;
    content += `\nmodule.exports = { ${flow.name} };\n`;
    
    return content;
  }

  /**
   * Reconstruct a single pattern instance
   */
  reconstructPattern(patternName, params) {
    return this.patternLibrary.expand(patternName, params);
  }

  /**
   * Verify reconstruction matches original
   */
  verify(originalContent, reconstructedContent) {
    // Normalize whitespace
    const normalize = (str) => str.replace(/\s+/g, ' ').trim();
    
    return normalize(originalContent) === normalize(reconstructedContent);
  }
}
